//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheXDS.Vivianne.Resources.Strings.Info.Audio {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class BnkFileInfoExtractor {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BnkFileInfoExtractor() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TheXDS.Vivianne.Resources.Strings.Info.Audio.BnkFileInfoExtractor", typeof(BnkFileInfoExtractor).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Declared streams: {0}.
        /// </summary>
        internal static string BnkFileNfo_DeclaredStreams {
            get {
                return ResourceManager.GetString("BnkFileNfo_DeclaredStreams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Streams with PT headers: {0}.
        /// </summary>
        internal static string BnkFileNfo_StreamsWithPtHeaders {
            get {
                return ResourceManager.GetString("BnkFileNfo_StreamsWithPtHeaders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total payload size: {0}.
        /// </summary>
        internal static string BnkFileNfo_TotalPayload {
            get {
                return ResourceManager.GetString("BnkFileNfo_TotalPayload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usable audio payload: {0}.
        /// </summary>
        internal static string BnkFileNfo_UsablePayload {
            get {
                return ResourceManager.GetString("BnkFileNfo_UsablePayload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BNK format version: {0}.
        /// </summary>
        internal static string BnkFileNfo_Version {
            get {
                return ResourceManager.GetString("BnkFileNfo_Version", resourceCulture);
            }
        }
    }
}
