namespace TheXDS.Vivianne.Resources.Strings.Codecs;

/// <summary>
///   A strongly-typed resource class, for looking up localized strings, etc.
/// </summary>
// This class was auto-generated by the Visual Studio Code Extension PrateekMahendrakar.resxpress
[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
public class RefPackCodec
{
	private static global::System.Resources.ResourceManager resourceMan;

	/// <summary>
	/// Initializes a new isntance of the <see cref="RefPackCodec"/> class.
	/// </summary>
	[global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
	public RefPackCodec()
	{
	}
	/// <summary>
	///   Returns the cached ResourceManager instance used by this class.
	/// </summary>
	[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
	public static global::System.Resources.ResourceManager ResourceManager
	{
		get
		{
			if (object.ReferenceEquals(resourceMan, null))
			{
				global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TheXDS.Vivianne.Resources.Strings.Codecs.RefPackCodec", typeof(RefPackCodec).Assembly);
				resourceMan = temp;
			}
			return resourceMan;
		}
	}
	/// <summary>
	///   Overrides the current thread's CurrentUICulture property for all
	///   resource lookups using this strongly typed resource class.
	/// </summary>
	[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
	public static global::System.Globalization.CultureInfo Culture { get; set; }
	
	/// <summary>
	/// Looks up a localized string similar to Something strange happened at the end of RefPack compression..
	/// </summary>
	public static string RefPackCompressError => ResourceManager.GetString("RefPackCompressError", Culture);
	
	/// <summary>
	/// Looks up a localized string similar to The data cannot be compressed. (You're better off using the uncompressed version of the file).
	/// </summary>
	public static string CouldNotCompress => ResourceManager.GetString("CouldNotCompress", Culture);
}
