//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheXDS.Vivianne.Resources.Strings.Info.Fce {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class FceInfoExtractor {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FceInfoExtractor() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TheXDS.Vivianne.Resources.Strings.Info.Fce.FceInfoExtractor", typeof(FceInfoExtractor).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of arts: {0}.
        /// </summary>
        internal static string FceNfo_Arts {
            get {
                return ResourceManager.GetString("FceNfo_Arts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bounding box size: X={0}, Y={1}, Z={2}.
        /// </summary>
        internal static string FceNfo_BoundingBox {
            get {
                return ResourceManager.GetString("FceNfo_BoundingBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Declared colors: {0}.
        /// </summary>
        internal static string FceNfo_DeclColors {
            get {
                return ResourceManager.GetString("FceNfo_DeclColors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dummies: {0}.
        /// </summary>
        internal static string FceNfo_Dummies {
            get {
                return ResourceManager.GetString("FceNfo_Dummies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File format: {0}.
        /// </summary>
        internal static string FceNfo_FileFormat {
            get {
                return ResourceManager.GetString("FceNfo_FileFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File signature: 0x{0:x8}.
        /// </summary>
        internal static string FceNfo_FileSignature {
            get {
                return ResourceManager.GetString("FceNfo_FileSignature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parts: {0}.
        /// </summary>
        internal static string FceNfo_Parts {
            get {
                return ResourceManager.GetString("FceNfo_Parts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reserved table 1.
        /// </summary>
        internal static string FceNfo_Rsvd1 {
            get {
                return ResourceManager.GetString("FceNfo_Rsvd1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reserved table 2.
        /// </summary>
        internal static string FceNfo_Rsvd2 {
            get {
                return ResourceManager.GetString("FceNfo_Rsvd2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reserved table 3.
        /// </summary>
        internal static string FceNfo_Rsvd3 {
            get {
                return ResourceManager.GetString("FceNfo_Rsvd3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} contents:.
        /// </summary>
        internal static string FceNfo_RsvdContents {
            get {
                return ResourceManager.GetString("FceNfo_RsvdContents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} size: {1}.
        /// </summary>
        internal static string FceNfo_RsvdSize {
            get {
                return ResourceManager.GetString("FceNfo_RsvdSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name: {0}.
        /// </summary>
        internal static string FcePartNfo_Name {
            get {
                return ResourceManager.GetString("FcePartNfo_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Origin: X={0}, Y={1}, Z={2}.
        /// </summary>
        internal static string FcePartNfo_Origin {
            get {
                return ResourceManager.GetString("FcePartNfo_Origin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Triangles: {0}.
        /// </summary>
        internal static string FcePartNfo_Triangles {
            get {
                return ResourceManager.GetString("FcePartNfo_Triangles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertices: {0}.
        /// </summary>
        internal static string FcePartNfo_Vertices {
            get {
                return ResourceManager.GetString("FcePartNfo_Vertices", resourceCulture);
            }
        }
    }
}
